title: mawi001
email: mwillemsma@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Martin Willemsma
  Automation craftsman
  Linux Ansible CI/CD docker kubernetes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mawi001.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alleskapot
github_username:  mawi001

# Build settings
markdown: kramdown

highlighter: rouge

remote_theme: "mmistakes/minimal-mistakes@4.14.2"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jemoji

# theme config
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      toc: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

timezone: Europe/Amsterdam

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

search: true

paginate: 5 # amount of posts to show
paginate_path: /page:num/

minimal_mistakes_skin: "neon"

# Site Author
author:
  name             : "Martin Willemsma"
  avatar           : "/assets/images/profile.jpeg"
  bio              : "Automate everything"
  location         : "Purmerend, NL"
  email            : mwillemsma@gmail.com
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/mwillemsma/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mawi001"


# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
